### ISSUE TITLE
feat(argocd): use Helm chart to declare argocd apps

### ISSUE THREAD

**Issue by ebuildy** [ebuildy/ansible-keployr#1]
Now:

- we declare all argocd app in a single YAML file

Todo:

- Use a simple Helm chart, with a single template "argocd-app.yaml" , and declare all applications into values.yml:
```
values.yaml:
  applications:
  - name: elasticsearch
     path: int/C2/elasticsearch
```
